# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Operacio.create(id: 1, descripcio_ca: "Quan sigui possible es realitzarà una inspecció directa dels fonaments. Quan aquests quedin ocults es valorarà el seu estat a partir de l’observació d’anomalies en altres elements estructurals i tancaments.", descripcio_es: "Cuando sea posible se realizará una inspección directa de los cimientos. Cuando éstos queden ocultos se valorará su estado a partir de la observación de anomalías en otros elementos estructurales y cerramientos.", periodicitat: 5, periodicitat_text_ca: "5 anys", periodicitat_text_es: "5 años", document_referencia: "EHE-08", responsable_ca: "Tècnic de capçalera", responsable_es: "Técnico de cabecera", obligatorietat: true, creat_usuari: false, sistema: "fonamentacio")
Operacio.create(id: 2, descripcio_ca: "Quan sigui possible es realitzarà una inspecció directa dels murs de contenció. Quan aquests quedin ocults es valorarà el seu estat a partir de l’observació d’anomalies en altres elements estructurals i tancaments.", descripcio_es: "Cuando sea posible se realizará una inspección directa de los muros de contención. Cuando éstos queden ocultos se valorará su estado a partir de la observación de anomalías en otros elementos estructurales y cerramientos.", periodicitat: 5, periodicitat_text_ca: "5 anys", periodicitat_text_es: "5 años", document_referencia: "EHE-08", responsable_ca: "Tècnic de capçalera", responsable_es: "Técnico de cabecera", obligatorietat: true, creat_usuari: false, sistema: "fonamentacio")
Operacio.create(id: 3, descripcio_ca: "Comprovació de l’estat general dels murs de contenció i el bon funcionament dels conductes de drenatge i de desguàs, així com l’absència d’humitats.", descripcio_es: "Comprobación del estado general de los muros de contención y el buen funcionamiento de los conductos de drenaje y de desagüe, así como la ausencia de humedades.", periodicitat: 1, periodicitat_text_ca: "1 any i cada vegada que hi hagi tormentes importants", periodicitat_text_es: "1 año y cada vez que se produzcan tormentas importantes", document_referencia: "DB-HS1", responsable_ca: "Tècnic de capçalera", responsable_es: "Técnico de cabecera", obligatorietat: true, creat_usuari: false, sistema: "fonamentacio")
Operacio.create(id: 4, descripcio_ca: "Comprovació de les obertures de ventilació de la càmera dels murs de contenció parcialment estancs per assegurar que no estan obstruïdes.", descripcio_es: "Comprobación de las aberturas de ventilación de la cámara de los muros de contención parcialmente estancos para asegurar que no están obstruidas.", periodicitat: 1, periodicitat_text_ca: "1 any", periodicitat_text_es: "1 año", document_referencia: "DB-HS1", responsable_ca: "Tècnic de capçalera", responsable_es: "Técnico de cabecera", obligatorietat: true, creat_usuari: false, sistema: "fonamentacio")
Operacio.create(id: 5, descripcio_ca: "Comprovació de l'estat de la impermeabilització interior dels murs de contenció.", descripcio_es: "Comprobación del estado de la impermeabilización interior de los muros de contención.", periodicitat: 1, periodicitat_text_ca: "1 any", periodicitat_text_es: "1 año", document_referencia: "DB-HS1", responsable_ca: "Tècnic de capçalera", responsable_es: "Técnico de cabecera", obligatorietat: true, creat_usuari: false, sistema: "fonamentacio")
Operacio.create(id: 6, descripcio_ca: "Inspecció general dels sostres sanitaris i soleres.", descripcio_es: "Inspección general de los forjados sanitarios y soleras.", periodicitat: 5, periodicitat_text_ca: "5 anys", periodicitat_text_es: "5 años", document_referencia: "EHE-08", responsable_ca: "Tècnic de capçalera", responsable_es: "Técnico de cabecera", obligatorietat: true, creat_usuari: false, sistema: "estructura")