class CreateParticions < ActiveRecord::Migration
  def change
    create_table :particions do |t|
      t.integer :edifici_id
      t.boolean :envans_ceramica
      t.boolean :envans_cartro_guix
      t.boolean :envans_bloc_formigo
      t.boolean :envans_paves
      t.boolean :envans_fusta
      t.boolean :envans_plaques_alveolades
      t.boolean :celras_fibres_vegetals
      t.boolean :celras_fibres_minerals
      t.boolean :celras_plaques_guix
      t.boolean :celras_metalic
      t.boolean :celras_fusta
      t.boolean :aillament_sota_sostre
      t.boolean :aillament_sobre_sostre
      t.boolean :aillament_plaques
      t.boolean :aillament_mantes
      t.boolean :aillament_amorf
      t.boolean :aillament_fibra_vidre
      t.boolean :aillament_polietile_reticulat
      t.boolean :aillament_llana_roca
      t.boolean :aillament_escuma_fenolica
      t.boolean :aillament_escuma_poliureta
      t.boolean :aillament_polietile_expandit
      t.boolean :aillament_fibres_textils
      t.boolean :aillament_argila_expandida
      t.boolean :aillament_escuma_melamina
      t.boolean :aillament_poliestire_extrudit
      t.boolean :aillament_celulosa
      t.boolean :aillament_perlita_expandida
      t.boolean :aillament_suro_aglomerat
      t.boolean :revestiment_vertical_enguixat
      t.boolean :revestiment_vertical_arrebossat
      t.boolean :revestiment_horitzontal_enguixat
      t.boolean :revestiment_horitzontal_arrebossat
      t.boolean :acabat_pintat
      t.boolean :acabat_aplacat_ceramica
      t.boolean :acabat_empaperat
      t.boolean :acabat_taulell_fusta
      t.boolean :acabat_sintetic
      t.boolean :acabat_textil
      t.boolean :acabat_estuc
      t.boolean :acabat_aplacat_pedra
      t.boolean :acabat_fusta
      t.boolean :acabat_suro
      t.boolean :paviment_formigo
      t.boolean :paviment_pedra_natural
      t.boolean :paviment_terratzo
      t.boolean :paviment_mosaic_hidraulic
      t.boolean :paviment_suro
      t.boolean :paviment_ceramica_natural
      t.boolean :paviment_ceramica_esmaltada
      t.boolean :paviment_gres_natural
      t.boolean :paviment_goma
      t.boolean :paviment_parquet_encolat
      t.boolean :paviment_parquet_flotant
      t.boolean :paviment_parquet_llates
      t.boolean :paviment_pvc
      t.boolean :paviment_moqueta
      t.boolean :paviment_linoleum
      t.boolean :porta_bastiment_fusta
      t.boolean :porta_bastiment_metalic
      t.boolean :porta_fulla_massissa_fusta
      t.boolean :porta_fulla_aplacat_fusta
      t.boolean :porta_fulla_vidre
      t.boolean :porta_fulla_alumini
      t.boolean :porta_fulla_ferro
      t.boolean :porta_acabat_pintat
      t.boolean :porta_acabat_lacat
      t.boolean :porta_acabat_envernissat
      t.boolean :porta_ferratge_llauto
      t.boolean :porta_ferratge_acer_llautonat
      t.boolean :porta_ferratge_acer_niquelat
      t.boolean :porta_ferratge_acer_inoxidable
      t.boolean :porta_ferratge_alumini
      t.boolean :barana_ferro_forjat
      t.boolean :barana_perfils_acer
      t.boolean :barana_perfils_alumini
      t.boolean :barana_fusta
      t.boolean :barana_pvc
      t.boolean :barana_vidre_laminat
      t.boolean :barana_metacrilat

      t.timestamps null: false
    end
  end
end
